DROP TABLE IF EXISTS SERVENTIA, CLIENTES, SERVIÇOS, SERVIDOR, MAQUINAS ,FUNCIONARIOS, RECEPCAO, PESSOAS;


CREATE TABLE SERVENTIA(
nomeServentia VARCHAR(20) NOT NULL PRIMARY KEY,
cidade VARCHAR(20) NOT NULL,
titular VARCHAR(20) NOT NULL
);

CREATE TABLE FUNCIONARIOS(
idFuncionarios INTEGER NOT NULL PRIMARY KEY,
cargo VARCHAR(20) NOT NULL, 
setor VARCHAR(20) NOT NULL,
FOREIGN KEY (setor) REFERENCES SERVENTIA(setor)	
);

CREATE TABLE SERVIÇOS(
idServiços INTEGER NOT NULL PRIMARY KEY,
cadastroPessoa VARCHAR(20),
tipoServiço VARCHAR(20),
naturezaServiço  VARCHAR(20),

FOREIGN KEY (cadastroPessoa) REFERENCES PESSOA(cpf)
);

CREATE TABLE PESSOAS(
cpf VARCHAR(20) NOT NULL PRIMARY KEY,
nome VARCHAR(20) NOT NULL,
telefone VARCHAR(20) NOT NULL

);

CREATE TABLE MAQUINAS(
idmaquina INTEGER NOT NULL PRIMARY KEY,
usuarioMaquina VARCHAR(20) NOT NULL,
numeroMac serial NOT NULL
);

CREATE TABLE SERVIDOR(
idServidor serial NOT NULL PRIMARY KEY,
nomeServidor VARCHAR(20) NOT NULL,
maquinasRegistradas INTEGER NOT NULL,
FOREIGN KEY (maquinasRegistradas) REFERENCES MAQUINAS(idmaquina)
);

CREATE TABLE RECEPCAO(
idAberturaderecepcao Serial NOT NULL PRIMARY KEY,
horarioAtendimento VARCHAR(20) NOT NULL,
atendente INTEGER NOT NULL,
FOREIGN KEY (atendente) REFERENCES FUNCIONARIOS(idfuncionario)
);

CREATE TABLE CLIENTES(
nomeCliente VARCHAR(20) NOT NULL PRIMARY KEY,
tipoPessoa VARCHAR(20) NOT NULL,
dadosCliente VARCHAR(20) NOT NULL,
FOREIGN KEY (dadosCliente) REFERENCES PESSOA(cpf) 
);

